server:
  port: ${PORT:8761}
  
spring:
  application:
    name: amabono-eureka

     
eureka:
  instance:
    prefer-ip-address: false
#    ip-address: ${CF_INSTANCE_IP}
    non-secure-port: 80
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45
  client:
    region: default
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/     