steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'amabono-api-gateway'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/golden-manifest-237210/amabono-api-gateway:$REVISION_ID', '.'] 
  dir: 'amabono-api-gateway'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/golden-manifest-237210/amabono-api-gateway:$REVISION_ID'] 
  dir: 'amabono-api-gateway'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/amabono-api-gateway'
  - 'amabono-api-gateway-sha256=gcr.io/golden-manifest-237210/amabono-api-gateway:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'    
   
  
