server:
  port: 8082
  
spring:
  application:
    name: amabono-activity-management
  datasource:
    url: jdbc:mysql://35.229.145.166/am
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: am
    password: am

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: 35.221.170.228
    port: 6379
    password: sDS+dY2p
