spring:
  application:
    name: amabono-api-gateway

server:
  port: ${PORT:8050}
    
zuul:
  ignored-services: '*'
  routes:
    amabono-activity: /activity/**


eureka:
  client:
    region: default
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/