steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'amabono-eureka'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/golden-manifest-237210/amabono-eureka:$REVISION_ID', '.'] 
  dir: 'amabono-eureka'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/golden-manifest-237210/amabono-eureka:$REVISION_ID'] 
  dir: 'amabono-eureka'
  
  
