server:
  port: 8081
  
 
  
spring:
  application:
    name: amabono-member
  datasource:
    url: jdbc:mysql://35.229.145.166/mem
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mem
    password: mem

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: 35.221.170.228
    port: 6379
    password: sDS+dY2p

eureka:
  client:
    region: default
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       