steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'amabono-member'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/golden-manifest-237210/amabono-member:$REVISION_ID', '.'] 
  dir: 'amabono-member'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/golden-manifest-237210/amabono-member:$REVISION_ID'] 
  dir: 'amabono-member'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/amabono-member'
  - '-n'
  - 'mall'
  - 'amabono-member-sha256=gcr.io/golden-manifest-237210/amabono-member:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'    
  
