server:
  port: 8083
  
spring:
  application:
    name: amabono-review
  datasource:
    url: jdbc:mysql://35.229.145.166/rv
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rv
    password: av

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: 35.221.170.228
    port: 6379
    password: sDS+dY2p

eureka:
  client:
    region: default
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    service-url:
      defaultZone: http://35.221.219.98:8761/eureka/

      
api:
  path : http://35.234.14.192:8050 